const searchInputPlaceholders = [
  '가장 관심있는 분야는 뭐에요?',
  'Frontend? Backend? Database?',
  '2024년 개발 트렌드',
  'Nextjs에서 성능 개선하는 방법',
  'JavaScript에서 성능 최적화 해봤나요?',
  '오늘은 어떤 코드를 작성할까요?',
  'Git 커밋 메시지를 더 잘 쓰는 방법?',
  'React에서 상태 관리를 어떻게 하나요?',
  '다음 프로젝트의 기술 스택은?',
  'TypeScript로 안전한 코드를 작성해보세요!',
  'NestJS로 서버를 더 효율적으로 관리하세요!',
  'REST API vs GraphQL: 무엇을 선택할까요?',
  '최고의 개발 생산성 도구는?',
  '코드 리팩토링, 지금이 최적의 타이밍!',
  'ESLint로 코드 품질을 높여보세요!',
  'Agile 방법론에 대해 얼마나 알고 있나요?',
  'CI/CD 파이프라인을 자동화하는 방법!',
  'CSS에서 가장 자주 쓰이는 Flexbox 트릭!',
  '테스트 커버리지를 더 높이는 방법?',
  'State management의 진화: Redux vs Recoil',
  'SaaS 개발에서 중요한 보안 체크리스트!',
  'AI가 개발자에게 주는 이점은?',
  '클라우드 인프라: AWS vs Azure vs GCP',
  'JAMstack이란 무엇인가요?',
  'Vite로 번들링 속도를 높여보세요!',
  'TDD로 더 나은 코드를 작성할 수 있을까요?',
  '최신 프레임워크 비교: Svelte vs Vue vs React',
  'API 속도를 개선할 수 있는 팁!',
  '프론트엔드에서 서버리스 활용하기!',
  'GraphQL 스키마 설계, 어떻게 해야 할까요?',
  'PWA로 웹앱의 성능을 한 단계 끌어올리세요!',
];

export default searchInputPlaceholders;
