// Meta
import type { Metadata } from 'next';

// style
import './globals.css';

// plugins
import NextTopLoader from 'nextjs-toploader';

// components
// import { ThemeProvider } from '@/components/context/theme-provider';
import Header from '@/components/screen/Header';
import Footer from '@/components/screen/Footer';

// fonts
import { pretendard } from '@/assets/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body className={`${pretendard.className} antialiased`}>
        <NextTopLoader color="#16a34a" shadow="0 0 10px #16a34a,0 0 5px #16a34a" />
        <div id="wrap" className="min-h-screen">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
